# Generated by Django 3.0.3 on 2020-08-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_subscriber1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber1',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
