# Generated by Django 3.0.3 on 2020-08-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200831_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
